---
- name: FreeBSD Development Setup
  hosts: localhost
  connection: local
  become: true

  vars_prompt:
    - name: become_password
      prompt: "Enter sudo password"
      private: yes

  tasks:
    - name: Update package repository
      community.general.pkgng:
        update_cache: yes

    - name: Install packages
      community.general.pkgng:
        name:
          - bat
          - bottom
          - curl
          - eza
          - fd
          - fzf
          - gh
          - git
          - go
          - gopls
          - htop
          - hyperfine
          - neovim
          - nmap
          - node
          - ripgrep
          - rust-analyzer
          - wget
          - zsh
        state: present

    - name: Install wezterm from ports
      community.general.pkgng:
        name: wezterm
        state: present
      ignore_errors: yes

    - name: Check current shell
      command: echo $SHELL
      register: current_shell
      changed_when: false
      failed_when: false

    - name: Add zsh to list of shells
      lineinfile:
        path: /etc/shells
        line: /usr/local/bin/zsh
        create: yes

    - name: Change user shell to zsh
      become: true
      ansible.builtin.user:
        name: "{{ target_user }}"
        shell: /usr/local/bin/zsh
      when: current_shell.stdout != '/usr/local/bin/zsh'
      ignore_errors: true

    - name: Check if rustup is installed
      command: which rustup
      register: rustup_check
      changed_when: false
      failed_when: false
      become: false

    - name: Install rustup
      shell: curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
      when: rustup_check.rc != 0
      become: false
